apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: exam-system
type: Opaque
stringData:
  DATABASE_URL: postgresql://exam_user:exam_password@postgres-service:5432/exam_management
  JWT_SECRET: dev_kubernetes_secret_change_later