name: Terraform Validate

on:
  push:
  pull_request:

jobs:
  terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/aws-eks

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform formatting
        run: terraform fmt -check

      - name: Initialize Terraform without backend
        run: terraform init -backend=false

      - name: Validate Terraform
        run: terraform validate